name: Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: build
        gradle-version: wrapper
    - name: Check
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: check
        gradle-version: wrapper
    - name: Test
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: test
        gradle-version: wrapper