name: Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Java 8
      run: sudo apt-get install openjdk-8-jdk
    - name: Run Gradle Build
      run: ./gradlew build
    - name: Run Gradle Check
      run: ./gradlew check
    - name: Run Gradle Test
      run: ./gradlew test